




.build/leonardo/src/FysDesGlove.cpp : src/FysDesGlove.ino
	@mkdir -p .build/leonardo/src
	@echo src/FysDesGlove.ino
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/leonardo/src/FysDesGlove.cpp
	@true

